vittoria's movies-project
Technigo/project-movies-vite pull request #56
Opened 2024-04-07 10:43 UTC by vittoriamatteoli

Netlify link
https://movie-magic-hub.netlify.app/

Collaborators
[vittoriamatteoli]

2024-04-10 15:03 UTC, HIPPIEKICK requested changes
Good job with this project Vittoria! Make sure it's responsive, and you're good to go.

2024-04-10 15:03 UTC, HIPPIEKICK commented on src/pages/SeriesDetails.jsx
Is there a reason you couldn't reuse the MoviesDetails component? 👀

2024-04-11 07:29 UTC, vittoriamatteoli commented on src/pages/EpisodesList.jsx
> +  const [episodes, SetEpisodes] = useState([])
fixed

2024-04-11 08:02 UTC, vittoriamatteoli commented on src/pages/SeriesDetails.jsx
There were some slight differences between the APIs , but I made it work in one MediaDetails.jsx now.

2024-04-22 15:50 UTC, HIPPIEKICK approved these changes

2024-04-23 08:24 UTC, vittoriamatteoli commented
I tried to remove the 100% width but it changes too much the style. I want the grey overlay lawyer to span all the hero section.

2025-01-03 15:55 UTC, closed without merging