Week 9 - project-movies-vite - Mai
Technigo/project-movies-vite pull request #66
Opened 2024-04-08 13:24 UTC by maikanetaka

Link:

https://project-movies-vite-mai.netlify.app/

2024-04-11 08:49 UTC, HIPPIEKICK commented on src/api.js
> +  }
I only see this right now - maybe there's something wrong with the deployed env variable (VITE_APP_API_KEY)? 👀

2024-05-17 13:30 UTC, AntonellaMorittu requested changes
Hello Mai, there is an error and the page doesn't render. Maybe there's something wrong with the deployed env variable (VITE_APP_API_KEY)? Please double-check, thanks :)

2024-05-19 19:19 UTC, maikanetaka commented
> Hello Mai, there is an error and the page doesn't render. Maybe there's something wrong with the deployed env variable (VITE_APP_API_KEY)? Please double-check, thanks :)

Hello @AntonellaMorittu and @HIPPIEKICK Sorry I missed this and now I have added env variable to netlify. Please check!

2024-05-21 12:49 UTC, HIPPIEKICK requested changes
Looking good! Would just like you to add some kind of Back-button as we have in our example, and you're good to go.

2024-05-21 12:49 UTC, HIPPIEKICK commented on src/App.jsx
>  };
Well structured app 👍

2024-06-18 09:58 UTC, maikanetaka commented
Hey @HIPPIEKICK, I have added the back button. Please check!

2024-06-19 14:02 UTC, AntonellaMorittu approved these changes

2025-01-03 15:55 UTC, closed without merging