Movies Sofie
Technigo/project-movies-vite pull request #67
Opened 2024-04-09 12:19 UTC by SofieFerrari

2024-04-11 08:50 UTC, HIPPIEKICK commented
Can you share a link to your deployed site? 😇

2024-04-13 19:58 UTC, SofieFerrari commented
Sure!! https://bucolic-kangaroo-37b00f.netlify.app/

2024-04-15 13:50 UTC, Caracal23 reviewed
Way to go Sofie!! 🚀
It is great to see how you manage this solo project; you should be proud of yourself!
Keep it up with the good code !! 
-Izabel&Etna

2024-04-15 13:50 UTC, Caracal23 commented on src/components/DetailList.jsx
> +						backgroundImage: `url(https://media.themoviedb.org/t/p/w780${detailData.backdrop_path})`,
Since there are screens that are bigger than 780; maybe next time you could consider on taking 1280px for background images.
-Izabel&Etna

2024-04-15 13:50 UTC, Caracal23 commented on src/components/Loader.jsx
> +// 	export const DelayLottie = setTimeout(() => {
For the next time you might want to consider creating the function "DelayLottie" before (for example, around line 5) and then you can call the function inside of the useEffect. 👍 
-Izabel&Etna

2024-04-15 13:50 UTC, Caracal23 commented on src/components/PopularList.jsx
> +					</Link>
Code looks great but it gets a bit complicated to read due to the unorganised set up. 
-Izabel&Etna

2024-04-15 13:50 UTC, Caracal23 commented on src/components/SecondPage.jsx
It is interesting how you split in two different components the fetching and the data rendering. Maybe you can explain us why you choose that logic 😊.
-Izabel&Etna

2024-04-15 13:50 UTC, Caracal23 commented on src/styling/PopularList.css
> +	justify-content: flex-end;
Just a question here...Did you want to present the movies all the way to right? or you want them to be center? 
-Izabel&Etna

2024-05-30 09:32 UTC, AntonellaMorittu requested changes
Please check:
- accessibility: needs to score at least 95
- [how to deploy routes ](https://www.notion.so/technigo/Zoom-recordings-852e9d63af0b40a6b9a63f21313c0d6c?pvs=4#1a10e0bb9eb24e668e508dd3b7062154)

2024-06-16 10:57 UTC, SofieFerrari commented
> Please check:
> 
> * accessibility: needs to score at least 95
> * [how to deploy routes ](https://www.notion.so/technigo/Zoom-recordings-852e9d63af0b40a6b9a63f21313c0d6c?pvs=4#1a10e0bb9eb24e668e508dd3b7062154)

Hi Antonella!
Thanks for checking!
I get 100% in both list and detalis now :D

2024-06-19 14:01 UTC, AntonellaMorittu requested changes
Hi Sofie, getting there, please deploy the routes adding the `netlify.toml` file and also please format the files 🪄

2024-06-20 13:02 UTC, AntonellaMorittu approved these changes

2025-01-03 15:55 UTC, closed without merging